name: Geem
version: 1.2.11
main: com.github.micha4w.Geem
author: micha4w
description: Geem, that's all
api-version: 1.17
commands:
  test:
    description: Don't use this
    usage: /test <confirmation>
    permission: geem.allowall

  updategeem:
    description: Grab Update from Github
    usage: /updategeem
    permission: geem.allowall

  addplayer:
    description: Add a player to geem
    usage: /addplayer <r/g/b/y> <player>
    permission: geem.allowall

  removeplayer:
    description: Remove a player from geem
    usage: /removeplayer <player>
    permission: geem.allowall

  prepare:
    description: Prepare a new world to play geem
    usage: /removeplayer <player>
    permission: geem.allowall

permissions:
  geem.allowall:
    description: Allows a player to do everything
    default: op